version: '2'

services:
  web:
    build: .
    environment:
      WEBSITE_TITLE: ${WEBSITE_TITLE}
      WEBSITE_HOME_CONTENT: ${WEBSITE_HOME_CONTENT}
      WEBSITE_NAV_LOGO: ${WEBSITE_NAV_LOGO}
      WEBSITE_APP_TITLE: ${WEBSITE_APP_TITLE}

      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}

      DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
      TOKEN_SECRET: ${TOKEN_SECRET}

      APP_URL: ${APP_URL}
      ASSETS_PATH: ${ASSETS_PATH}

    depends_on:
      - db
    ports:
      - "8080:80"
    entrypoint: ./scripts/wait.sh db:5432 -- npm start
    volumes:
      - ./releases:/usr/src/electron-release-server/releases
    networks:
      - localnet

  db:
    image: postgres:11
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - localnet

volumes:
  postgres:

networks:
  localnet:
    driver: bridge
